# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "ainory"
description: ainory dev blog
avatar: https://ainory.github.io/images/icon.jpg

# URL
url: http://ainory.github.io
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "//ainory.github.io/about"
  #- name:           "Download"
  #  href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
